### ISSUE TITLE
goetime.com in urlshortener?

### ISSUE THREAD

**Issue by spirillen** [cbuijs/shallalist#1]
Hi @cbuijs I can see in https://github.com/cbuijs/shallalist/blob/master/urlshortener/domains that you have goetime.com listed, but from a quick review of that site it looks more like tracking software... Do you have any information to share on this?

for own ref: https://github.com/spirillen/rpz-block-list/issues/69

**Comment by cbuijs** [comment]
Hi @spirillen,

I do not maintain these lists, I just provide an unpacked version of ShallaList that can be found here: http://www.shallalist.de/

You might contact someone there to re-assess this entry. I did a quick check and I think you are right. But then most if not all URL redirectors are.

-Chris.
