### ISSUE TITLE
us8.mailchimp.com (false positive)

### ISSUE THREAD

**Issue by BanijaDev** [cbuijs/shallalist#10]
![image](https://user-images.githubusercontent.com/97141433/148316994-430f0955-c263-401f-86e6-1564a450686f.png)

this domain use for email subscription from porkbun

**Comment by cbuijs** [comment]
Hi @BanijaDev,

Thanks for the notification, appreciated.

Just to inform you, I am NOT the maintainer of these lists, I just provide a repo with an unpacked/optimized version without touching the content.

To make the maintainers aware, you can contact them via here:

Website: http://www.shalla.de/impressum.html
Email: info@shalla.de

Cheers,
-Chris.

**Comment by BanijaDev** [comment]
![Screenshot_20220111-144648543.jpg](https://user-images.githubusercontent.com/97141433/148901652-0d8a74ba-1366-4f79-887d-ab72f5e97c76.jpg)

**Comment by cbuijs** [comment]
Works here. Maybe email them?

![image](https://user-images.githubusercontent.com/6727250/148902026-2dad4e34-426d-4e42-a3ce-8ded2b08a066.png)
