### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by totalimmersion** [cbuijs/shallalist#11]
Hi, I found a false positive on your spyware list. The cloom.com domain is listed there, but should not be blocked. Could you remove the cloom.com from the list?
https://github.com/cbuijs/shallalist/blob/96be9d40ebf02bb25bb94f44a47f03a1e72d5128/spyware/domains#L3769

Thanks in advance.

**Comment by cbuijs** [comment]
Hi @totalimmersion,

Thanks for the notification, appreciated.

Just to inform you, I am NOT the maintainer of these lists, I just provide a repo with an unpacked/optimized version without touching the content.

To make the maintainers aware, you can contact them via here:

Website: http://www.shalla.de/impressum.html
Email: [info@shalla.de](mailto:info@shalla.de)

Cheers,
-Chris.
