### ISSUE TITLE
TLD false entry

### ISSUE THREAD

**Issue by ngadmini** [cbuijs/shallalist#12]
Halo @cbuijs 
https://github.com/cbuijs/shallalist/blob/96be9d40ebf02bb25bb94f44a47f03a1e72d5128/gamble/domains#L11441
maybe fixed with
`sed -i.bak "s/^rubypalacegoldengame\.$/rubypalacegolden\.game/g" gamble/domains`

tq.

**Comment by cbuijs** [comment]
Hi @ngadmini,

Thanks for the notification/heads-up, appreciated!

Just to inform you, I am NOT the maintainer of these lists, I just provide a repo with an unpacked/optimized version without touching the content.

To make the maintainers aware, you can contact them via below website/email:

Website: http://www.shalla.de/impressum.html
Email: [info@shalla.de](mailto:info@shalla.de)

Cheers,
-Chris.
