### ISSUE TITLE
unity3d.com

### ISSUE THREAD

**Issue by p1r473** [cbuijs/shallalist#13]
This is a game development engine/software
This is a false positive
Thanks

**Comment by cbuijs** [comment]
Hi @p1r473 ,

Note that I am not the maintainer of this lists.

But... These lists are not only intended as block-lists. Can also be used as allow-lists or for categorization. In that respect I do not think it is a false positive.

As said. I am not the maintainer, you can reach out to the original maintainers here: https://shallalist.de

Thanks for being it up though!

Cheers,
-Chris

**Comment by p1r473** [comment]
Looks like shallalist is long gone :)

**Comment by cbuijs** [comment]
My Mistake, the right URL is: http://www.shalla.de/impressum.html

**Comment by p1r473** [comment]
Reported upstream, thanks
