### ISSUE TITLE
Invalid domain in adv list

### ISSUE THREAD

**Issue by whoot** [cbuijs/shallalist#5]
Hey,
there seems to be an invalid domain in the adv list:

```
  [i] Target: https://raw.githubusercontent.com/cbuijs/shallalist/master/adv/domains
  [✓] Status: Retrieval successful
  [i] Received 14315 domains, 1 domains invalid!
      Sample of invalid domains:
      - kosbind.co]
```

You may want to change it to `kosbind.co` or delete it as I could not resolve it.

Regards

**Comment by cbuijs** [comment]
Hi @whoot ,

I do not maintain these lists, I just provide a github-repo of the unpacked versions of it.

The originator/source of the lists is here: http://www.shallalist.de/
They can be contacted on: http://www.shalla.de/impressum.html

Hope this helps.
Cheers,
-Chris.
