### ISSUE TITLE
No blacklists on the repository

### ISSUE THREAD

**Issue by Firerust96** [cbuijs/shallalist#7]
I tried to download blacklists from this repo but it seems to no longer have them. I tried to access shallalist page but it's not working, any news?

**Comment by cbuijs** [comment]
Hi @Firerust96 ,

I will check. Seems that the shallalist.de site is down and the lists are unavaible for the moment. It should come back automatically when they recover.

I will make sure that the latest version stays here when this happens again.

-Chris.

**Comment by cbuijs** [comment]
Fixed.
