### ISSUE TITLE
anibis.ch in ADV

### ISSUE THREAD

**Issue by crssi** [cbuijs/shallalist#8]
Is the `anibis.ch` really ADV?

It seem to me as secondhand market site.

Cheers

**Comment by cbuijs** [comment]
Hey @crssi,

Thanks for reporting, but I am **NOT** the maintainer of these lists, I just provide a unpacked version as repo on GitHub :-).

Not sure why `anibis.ch` is flagged as/for ads, I don't see it in any other (popular ad) lists, so it is probably a false-positive indeed.

You can let the people at Shallalist know at this page: http://www.shalla.de/impressum.html

Cheers,
-Chris.
