### ISSUE TITLE
[Feature]: Leverage GitHub CI and DNSX to efficiently scan for any live hosts and create lists for them.

### ISSUE THREAD

**Issue by T145** [cbuijs/shallalist#9]
I've used SquidGuard lists like Shallalist and UT Capitole before but found them to have a suprising amount of dead hosts, even though they're frequently updated. I just assumed that due to the frequent updates the hosts would be live, but it just goes to show that you can't assume much.

I have a similar project called [San Junipero](https://github.com/T145/san-junipero) that currently handles some UT Capitole blacklists which you could use as a template.

You can use my Black Mirror Docker image as it's been preloaded with all the necessary programs.

Side note, you can also set up GitHub CI to handle the archive extraction and list organization.

**Comment by cbuijs** [comment]
Hi @T145,

Thanks for the heads-up, appreciated!

I will look at it, and see if I can utilize it, probably build a new repo out of it as the purpose of this repo is just to provide an unpacked version of the lists and there is quite some usage and want to avoid risk breaking something (for whatever reason).

I looked at [pyfunceble](https://github.com/funilrys/PyFunceble) (as another example) in the past too. The problem I am having is that the resources needed to validate the domains is outside of my purpose. It is also quite slow.

What I do instead is compare against the top-1M queried domain-lists out there to see what is actually used (and just disregard the rest) as a less intense (faster) version with very similar/same outcomes/purpose.

See the TOP consolidated list I create every day to compare against, here:
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/top.list

Or the singular output of the individual sources I use:
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/domcop-top.list
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/majestic-top.list
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/statvoo-top.list
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/tranco-top.list
https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/umbrella-top.list

Thanks again for your note and project!
-Chris
